name: Contentful Migration Example

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    name: Contentful Migration Example
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v1

    - name: Contentful Migration
      id: migrate
      uses: ./
      with:
        delete_feature: true
        set_alias: false
        master_pattern: "master-[YY]-[MM]-[DD]-[hh]-[mm]"
        feature_pattern: "sandbox-[branch]"
        version_field: version
        version_content_type: versionTracking
        migrations_dir: test-migrations
      env: # Set the secret as an input
        SPACE_ID: ${{ secrets.SPACE_ID }}
        MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          See changes to the [${{steps.migrate.outputs.environment_name }} ][1] Environment on Contentful.

          [1]: ${{steps.migrate.outputs.environment_url}}
